apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
spec:
  type: LoadBalancer
  # use your external IP here
  loadBalancerIP: 35.194.153.92
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    name: web
